### ISSUE TITLE
[Go] Panic when importing different versions of Arrow Flight in the same project (v12, v13)

### ISSUE THREAD

**Issue by phillipleblanc** [apache/arrow-go#48]
### Describe the bug, including details regarding any error messages, version, and platform.

Importing both `github.com/apache/arrow/go/v12/arrow/flight` and `github.com/apache/arrow/go/v13/arrow/flight` into the same project causes a panic on startup due to a protobuf namespace conflict:

```
panic: proto: file "Flight.proto" is already registered
	previously from: "github.com/apache/arrow/go/v12/arrow/flight/internal/flight"
	currently from:  "github.com/apache/arrow/go/v13/arrow/flight/internal/flight"
See https://protobuf.dev/reference/go/faq#namespace-conflict


goroutine 1 [running]:
google.golang.org/protobuf/reflect/protoregistry.glob..func1({0x3f49720?, 0xc000bfa010?}, {0x3f49720?, 0xc000bfa060})
	/go/pkg/mod/google.golang.org/protobuf@v1.31.0/reflect/protoregistry/registry.go:56 +0x1e5
google.golang.org/protobuf/reflect/protoregistry.(*Files).RegisterFile(0xc000012810, {0x3f9a3f8?, 0xc0013281c0?})
	/go/pkg/mod/google.golang.org/protobuf@v1.31.0/reflect/protoregistry/registry.go:130 +0x3a6
google.golang.org/protobuf/internal/filedesc.Builder.Build({{0x358b83d, 0x3b}, {0x5af6de0, 0xb4d, 0xb4d}, 0x2, 0x13, 0x0, 0x1, {0x3f567a8, ...}, ...})
	/go/pkg/mod/google.golang.org/protobuf@v1.31.0/internal/filedesc/build.go:112 +0x1d6
google.golang.org/protobuf/internal/filetype.Builder.Build({{{0x358b83d, 0x3b}, {0x5af6de0, 0xb4d, 0xb4d}, 0x2, 0x13, 0x0, 0x1, {0x0, ...}, ...}, ...})
	/go/pkg/mod/google.golang.org/protobuf@v1.31.0/internal/filetype/build.go:138 +0x199
github.com/apache/arrow/go/v13/arrow/flight/internal/flight.file_Flight_proto_init()
	/go/pkg/mod/github.com/apache/arrow/go/v13@v13.0.0/arrow/flight/internal/flight/Flight.pb.go:1792 +0x1b8
github.com/apache/arrow/go/v13/arrow/flight/internal/flight.init.0()
	/go/pkg/mod/github.com/apache/arrow/go/v13@v13.0.0/arrow/flight/internal/flight/Flight.pb.go:1543 +0xf
```

### Component(s)

Go

**Comment by zeroshade** [comment]
Closing as stale / known limitation.

This report references the retired monorepo packages `github.com/apache/arrow/go/v12` and `.../v13`. Arrow Go has since moved to the standalone `github.com/apache/arrow-go` module.

The root cause is the documented protobuf global-registry behavior (https://protobuf.dev/reference/go/faq#namespace-conflict): the generated `Flight.proto` descriptor registers under a fixed global name, so importing two major versions that both register it will always panic. This is inherent to `protoc-gen-go` global registration and is not specific to Arrow.

The only real fix would be to extract the generated Flight protobuf code into its own separately-versioned module shared across Arrow versions — an invasive change to the module layout and release process that we are not planning to pursue. In practice, projects should depend on a single major version of the Flight bindings. If consolidating the generated proto into a shared module becomes worthwhile, it can be tracked as a dedicated proposal.
